from .backgrounds.fractal import Mandelbrot
from .backgrounds.golden import Golden
from .backgrounds.julia import Julia
from .backgrounds.lavalamp import LavaLamp
from .backgrounds.plasma import Plasma
from .backgrounds.warp import Warp
from .console import Console
from .fonttest.fonttest import FontTest
from .fourjacks.fourjacksgameboard import FourJacksGameBoard
from .fourjacks.fourjacksgameover import FourJacksGameOver
from .fourjacks.fourjackstitle import FourJacksTitle
from .gameselect import GameSelect
from .jackblackjack.jackblackjack import JackBlackJack
from .jackblackjack.jackblackjacktitle import JackBlackJackTitle
from .jackdefense.jackdefensegameboard import JackDefenseGameBoard
from .jackdefense.jackdefensegameover import JackDefenseGameOver
from .jackdefense.jackdefensetitle import JackDefenseTitle
from .jackgames import JackGames
from .jackninjas.jackninjas import JackNinjas
from .jackninjas.jackninjaseditor import JackNinjasEditor
from .jackninjas.jackninjasinventory import JackNinjasInventory
from .jackninjas.jackninjastitle import JackNinjasTitle
from .jackninjas.jackninjaswinner import JackNinjasWinner
from .jackwizards.jackwizards import JackWizards
from .jackwizards.jackwizardsmap import JackWizardsMap
from .multitest.multitest import MultiTest
from .quadblox.quadblox import QuadBlox
from .quadblox.quadleadearboard import QuadLeaderboard
from .quadblox.quadmenu import QuadMenu
from .raycaster.raycaster import RayCaster
from .superball.superballfield import SuperBallField
from .superball.superballtitle import SuperBallTitle
from .tvstatic import TVStatic
from .viagalactica.vialevel import ViaLevel
from .viagalactica.viastarfield import ViaStarfield
from .viagalactica.viatitle import ViaTitle
from scenes.debug import Debug
from scenes.logo import Logo
from scenes.menu import Menu

from .solitaire.solitaire import Solitaire # auto-generated
from .triballer.triballer import TriBaller
from .geometryblast.geometryblast import GeometryBlast